version: 1.1.{build}-alpha
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
before_build:
  - dotnet restore
build:
  verbosity: normal
after_build:
  - dotnet pack NeuralNetwork.Structure.Contract -v=n /p:Configuration=Release /p:PackageVersion=%APPVEYOR_BUILD_VERSION%
artifacts:
- path: '**\*.nupkg'
  name: NuGet Packages
deploy:
  provider: NuGet
  api_key:
    secure: WMyqg8N2dXtblpP7+rRZmP1i1GnqMrHNEFnGEVqHsCG7O6HWc8fEkKd22Fh5MDx2
  artifact: /.*\.nupkg/
  on:
    branch: 1.1